# Generated by Django 2.1.3 on 2018-11-05 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_salida', models.DateField()),
                ('descripcion', models.CharField(max_length=120)),
                ('cantidad_canciones', models.IntegerField()),
                ('nombre_integrantes', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apodo', models.CharField(max_length=60)),
                ('anios', models.IntegerField()),
                ('profesion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Album')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Artista')),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='albums',
            field=models.ManyToManyField(through='albums.Cancion', to='albums.Album'),
        ),
    ]
